# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/sm1-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter sm1,$(TARGET_AMLOGIC_SOC)),)

endif
