# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/sm1-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/sm1-common

PRODUCT_COPY_FILES += \
    vendor/amlogic/sm1-common/proprietary/product/etc/permissions/privapp-permissions-atv-product.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-atv-product.xml \
    vendor/amlogic/sm1-common/proprietary/product/etc/permissions/privapp-permissions-deadpool.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-deadpool.xml \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/bluetooth/auto_pairing.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/auto_pairing.conf \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/bluetooth/blacklist.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/blacklist.conf \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor.conf \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/bluetooth/bt_vendor_usb.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor_usb.conf \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-droidlogic.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.dumpstate@1.1-service.droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.dumpstate@1.1-service.droidlogic.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.4-service.droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.4-service.droidlogic.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.droidlogic.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/android.hardware.usb.gadget@1.2-service.droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget@1.2-service.droidlogic.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/bluetooth.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bluetooth.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/dvb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dvb.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/fs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fs.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/irblaster1.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/irblaster1.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/power.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/power.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/sysfs_permissions.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sysfs_permissions.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/init/systemcontrol.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/systemcontrol.rc \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/lowmemorykiller.txt:$(TARGET_COPY_OUT_VENDOR)/etc/lowmemorykiller.txt \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/lowmemorykiller_2G.txt:$(TARGET_COPY_OUT_VENDOR)/etc/lowmemorykiller_2G.txt \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/lowmemorykiller_512M.txt:$(TARGET_COPY_OUT_VENDOR)/etc/lowmemorykiller_512M.txt \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/permissions/android.software.cant_save_state.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.cant_save_state.xml \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/remote.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/remote.cfg \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/remote.tab1:$(TARGET_COPY_OUT_VENDOR)/etc/remote.tab1 \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/remote.tab2:$(TARGET_COPY_OUT_VENDOR)/etc/remote.tab2 \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/remote.tab3:$(TARGET_COPY_OUT_VENDOR)/etc/remote.tab3 \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/thermal_info_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config.json \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/wifi/p2p_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant.conf \
    vendor/amlogic/sm1-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/amlogic/sm1-common/proprietary/vendor_dlkm/lib/modules/amlogic_fbc_lib.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/amlogic_fbc_lib.ko

PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.1-resources-vendor \
    android.hardware.graphics.composer@2.2-resources-vendor \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    android.hardware.bluetooth@1.0-impl-droidlogic \
    android.hardware.graphics.allocator@4.0-impl-arm \
    android.hardware.graphics.mapper@4.0-impl-arm \
    audio.primary.amlogic \
    camera.amlogic \
    hdmi_cec.amlogic \
    hwcomposer.amlogic \
    memtrack.amlogic \
    screen_source.amlogic \
    libAmlAudioOutPort \
    libOmxAudio \
    libOmxBase \
    libOmxCore \
    libOmxVideo \
    libam_adp \
    libamadec \
    libamaudioutils \
    libamavutils \
    libamgralloc_ext \
    libamladecs \
    libamlaudiohal.7.0 \
    libamlaudiorc \
    libamlparser \
    libamlresampler \
    libamlspeed \
    libamltinyalsa \
    libdatachunkqueue_alt \
    libdroidaudiospdif \
    libdsm \
    libdvbaudioutils \
    libfaad \
    libfbc \
    libfpscalculator_alt \
    libge2d \
    libicuuc_vendor \
    libispaaa \
    libmad \
    libmediahal_mediasync \
    libmediahal_passthrough \
    libmediahal_resman \
    libmediahal_tsplayer \
    libmediahal_tunnelrenderer \
    libmediahal_videodec \
    libmeson_display_adapter_remote \
    libmeson_display_service \
    libms12api_v24 \
    libnano \
    libomx_av_core_alt \
    libomx_clock_utils_alt \
    libomx_framework_alt \
    libomx_timed_task_queue_alt \
    libomx_worker_peer_alt \
    libpqcontrol \
    libsonic_ext \
    libstagefrighthw \
    libsystemcontrolservice \
    libthreadworker_alt \
    libvideotunnel \
    libwvhidl \
    libavl \
    libbalance \
    libdbx \
    libhpeqwrapper \
    libms12dapwrapper \
    libsrswrapper \
    libtreblebasswrapper \
    libvirtualsurround \
    libvirtualx \
    vendor.amlogic.display.meson_display_ipc@1.0 \
    vendor.amlogic.hardware.droidvold@1.0 \
    vendor.amlogic.hardware.systemcontrol@1.0 \
    vendor.amlogic.hardware.systemcontrol@1.1 \
    vendor.amlogic.hardware.tvserver@1.0 \
    Adt3LauncherCustomization \
    DeadpoolService \
    android.hardware.dumpstate@1.1-service.droidlogic.xml \
    android.hardware.graphics.composer@2.4-service.droidlogic.xml \
    android.hardware.thermal@2.0-service.droidlogic.xml \
    android.hardware.usb.gadget@1.2-service.droidlogic.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    DecInfo_test \
    ddrtest \
    esplayer \
    hdcp_tx22 \
    android.hardware.bluetooth@1.0-service-droidlogic \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.dumpstate@1.1-service.droidlogic \
    android.hardware.graphics.allocator@4.0-service \
    android.hardware.graphics.composer@2.4-service.droidlogic \
    android.hardware.thermal@2.0-service.droidlogic \
    android.hardware.usb.gadget@1.2-service.droidlogic \
    remotecfg \
    systemcontrol

PRODUCT_PACKAGES += \
    libGLES_mali_vulkan.amlogic_symlink32
